# Generated by Django 4.1.7 on 2023-03-03 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=205)),
                ('dni', models.CharField(max_length=205)),
                ('tel', models.CharField(max_length=205)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('observations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity', models.CharField(max_length=205)),
                ('name', models.CharField(max_length=205)),
                ('type_room', models.CharField(max_length=205)),
                ('state', models.IntegerField(choices=[(1, 'free'), (2, 'occupied')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'success'), (2, 'warning'), (3, 'danger')], default=1)),
                ('passanger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.passanger')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('number', models.CharField(max_length=20)),
                ('amount_people', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'reserved'), (2, 'check-in'), (3, 'check-out')])),
                ('observations', models.TextField()),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
                ('passanger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.passanger')),
            ],
        ),
    ]
