# Generated by Django 4.1.7 on 2023-03-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_room_passanger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('clean', '#9bf0ac'), ('dirty', '#fffb8f'), ('blocked', '#e74a3b')], default='clean', max_length=7),
        ),
    ]
