# Generated by Django 4.1.7 on 2023-03-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_room_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Room',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='status',
            new_name='status_res',
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('#9bf0ac', 'clean'), ('#fffb8f', 'dirty'), ('#e74a3b', 'blocked')], default='#9bf0ac', max_length=7),
        ),
    ]
