# Generated by Django 4.1.7 on 2023-03-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_rename_room_reservation_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='passanger',
            field=models.CharField(max_length=205, null=True),
        ),
    ]
