# Generated by Django 4.1.7 on 2023-03-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_room_passanger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='passanger',
        ),
    ]
