# Generated by Django 4.1.7 on 2023-03-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_room_passanger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('#9bf0ac', 'clean'), ('#fffb8f', 'dirty'), ('#D47777', 'blocked')], default='#9bf0ac', max_length=7),
        ),
    ]
