# Generated by Django 4.1.7 on 2023-03-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='passanger',
        ),
        migrations.AddField(
            model_name='passanger',
            name='adress',
            field=models.CharField(blank=True, max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='passanger',
            name='city',
            field=models.CharField(blank=True, max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='passanger',
            name='country',
            field=models.CharField(blank=True, max_length=205, null=True),
        ),
        migrations.AlterField(
            model_name='passanger',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='passanger',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
