# Generated by Django 4.1.7 on 2023-03-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_passanger_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
