# Generated by Django 4.1.7 on 2023-03-15 14:40

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_room_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=6, max_length=6, prefix=''),
        ),
    ]
