# Generated by Django 4.1.7 on 2023-03-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_alter_reservation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status_res',
            field=models.IntegerField(choices=[(1, 'reserved'), (2, 'check-in'), (3, 'check-out')], default='not-reserved'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type_room',
            field=models.CharField(choices=[(1, 'Sgl'), (2, 'Dbl'), (3, 'Tpl'), (4, 'Qdpl')], default=1, max_length=205),
        ),
    ]
