# Generated by Django 4.1.7 on 2023-04-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_alter_reservation_type_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status_res',
            field=models.IntegerField(choices=[(1, 'reserved'), (2, 'check-in'), (3, 'check-out'), (4, 'no-show')], default='not-reserved'),
        ),
    ]
