# Generated by Django 4.1.7 on 2024-01-17 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0020_alter_reservation_room_alter_reservation_status_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='Till',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('till_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method', models.CharField(choices=[('1', 'Cash'), ('2', 'Credit Card')], default=1, max_length=7)),
                ('amount', models.IntegerField()),
                ('observation', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_till', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.till')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Till',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('observation', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('item_till', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.till')),
            ],
        ),
    ]
