# Generated by Django 4.1.7 on 2024-01-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_till',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_method',
            field=models.CharField(max_length=25),
        ),
    ]
