# Generated by Django 4.1.7 on 2024-01-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_alter_item_till_name_alter_payment_pay_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
